### ISSUE TITLE
Transformer config with camel cased columns fails

### ISSUE THREAD

**Issue by divyenduz** [xataio/pgstream#277]
![Image](https://github.com/user-attachments/assets/6a8695f3-4025-4924-89bd-dd34919adf1d)

The underlying column exists and is "firstName" with a capital N. The transform config looks like this

```yaml
transformations:
  - schema: public
    table: User
    column_transformers:
      email:
        name: masking
        parameters:
          type: email
      firstName:
        name: greenmask_firstname
        parameters:
          generator: deterministic
          gender: Any
      lastName:
        name: neosync_firstname
        parameters:
          seed: 99

```
