### ISSUE TITLE
Escape hatch transform

### ISSUE THREAD

**Issue by divyenduz** [xataio/pgstream#311]
If we don't support a type that needs to be anonymized. There should be a way to not return that column to onboard a user successfully. Example, let's say a user has heart rates in a GeoJSON activity stored in JSONB format. 

Escape hatches like
- masking: don't work for all types and doesn't adhere to uniqueness constraints
- uuid: doesn't work for all types (and therefore doesn't work for jsonb)

Maybe an escape hatch can be to hardcode a response, something like,

```
transformations:
  validation_mode: relaxed
  table_transformers:
    - schema: public
      table: Project
      column_transformers:
        heart_rates:
          name: literal or hardcode (I like literal more)
          parameters:
            value: '{}'
```

This will be a escape hatch that would work on all the types (though won't be useful when uniqueness constraint is present). This is just a suggestion, maybe there are other ways around it.
