### ISSUE TITLE
[Bug] snapshot command fails when using configuration file in `snapshot_and_replication` mode

### ISSUE THREAD

**Issue by AcidFlow** [xataio/pgstream#331]
## Summary

When running the snapshot command using a configuration file (YAML), for which the mode is `snapshot_and_replication` the application exits with code 1, and the following error:

```
Error: source snapshot not configured
```

## Relevant Information

Version: 0.5.0

## Steps to reproduce

1. Create a configuration `config-example.yaml`

```yaml
source:
  postgres:
    url: "postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable"
    mode: "snapshot_and_replication" # options are replication, snapshot or snapshot_and_replication
    snapshot: # when mode is snapshot or snapshot_and_replication
      mode: full # options are data_and, schema or data
      tables: [
        "public.table_1",
      ] # tables to snapshot, can be a list of table names or a pattern
      recorder:
        repeatable_snapshots: false # whether to repeat snapshots that have already been taken. Defaults to false
        # postgres_url: "postgresql://user:password@localhost:5432/mytargetdatabase" # URL of the database where the snapshot status is recorded
        postgres_url: "postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable"
      snapshot_workers: 4 # number of schemas to be snapshotted in parallel. Defaults to 1
      data: # when mode is full or data
        schema_workers: 4 # number of schema tables to be snapshotted in parallel. Defaults to 4
        table_workers: 4 # number of workers to snapshot a table in parallel. Defaults to 4
        batch_page_size: 1000 # number of pages to read per batch. Defaults to 1000
      schema: # when mode is full or schema
        mode: "pgdump_pgrestore" # options are pgdump_pgrestore or schemalog
        pgdump_pgrestore:
          clean_target_db: true # whether to clean the target database before restoring
    replication: # when mode is replication or snapshot_and_replication
      replication_slot: "pgstream_slot"

target:
  postgres:
    url: "postgresql://postgres:postgres@localhost:5433/postgres?sslmode=disable"
    schema_log_store_url: "postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable"
    batch:
      timeout: 5000 # batch timeout in milliseconds. Defaults to 1s
      size: 5000 # number of messages in a batch. Defaults to 100
      max_bytes: 33554432 # max size of batch in bytes (1.5MiB). Defaults to 1.5MiB
      max_queue_bytes: 104857600 # max size of memory guard queue in bytes (100MiB). Defaults to 100MiB
    disable_triggers: false # whether to disable triggers on the target database. Defaults to false
    on_conflict_action: "nothing" # options are update, nothing or error. Defaults to error
```

2. Execute pgstream: `pgstream snapshot --config ./config-example.yaml`
3. The application exits with code 1, and the mentionned error.

## Expected behavior

When using the `snapshot_and_replication` and replication mode in the config file, the snapshot command should be able to run.

## Investigation

The configuration seem to be correctly parsed, however the snapshot command tries to access the `config.Listener.Snapshot` which is `nil` since the snapshot configuration is stored under `config.Listener.Postgres.Snapshot`.

See: https://github.com/xataio/pgstream/blob/81e85db04e18fbaa9dd27939732e9482d9ba224b/pkg/stream/stream_snapshot.go#L18
