### ISSUE TITLE
Add dynamic parameter support for phone codes/prefix

### ISSUE THREAD

**Issue by agedemenli** [xataio/pgstream#344]
Prefix parameter for phone number transformer can be fetched from another column.
Example config:

```
transformations:
    table_transformers:
    - schema: public
        table: users
        column_transformers:
        mobile_number:
            name: phone_number
            dynamic_parameters:
            prefix:
                column: country_code
```
